version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse

  nlp:
    build:
      context: ./services/nlp
    environment:
      - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8001:8001"

  api:
    build:
      context: ./services/api
    environment:
      - CLICKHOUSE_URL=${CLICKHOUSE_URL}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    depends_on:
      - clickhouse
    ports:
      - "8000:8000"

  web:
    build:
      context: ./services/web
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    ports:
      - "3000:3000"
    depends_on:
      - api
